[project]
name = "k3s-ansible"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible==13.4.0",
    "ansible-dev-tools==26.2.0",
    "kubernetes==35.0.0",
    "netaddr==1.3.0",
]
