[project]
name = "k3s-ansible"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible==13.2.0",
    "ansible-dev-tools==25.12.0",
    "kubernetes==34.1.0",
]
