disable-helm-controller: true
disable-kube-proxy: true
disable-network-policy: true
disable:
  - servicelb
  - traefik
flannel-backend: "none"
kube-apiserver-arg:
  - "admission-control-config-file=/var/lib/rancher/k3s/server/admission-configuration.yaml"
  - "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
  - "audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml"
  - "audit-log-maxage=30"
  - "audit-log-maxbackup=10"
  - "audit-log-maxsize=100"
  - "enable-admission-plugins=NodeRestriction,EventRateLimit"
  - "service-account-extend-token-expiration=false"
  # MutatingAdmissionPolicy
  - "feature-gates=MutatingAdmissionPolicy=true"
  - "runtime-config=admissionregistration.k8s.io/v1beta1=true"
kube-controller-manager-arg:
  - "terminated-pod-gc-threshold=100"
kubelet-arg:
  - "streaming-connection-idle-timeout=5m"
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
protect-kernel-defaults: true
secrets-encryption: true
