- name: Create k3s directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s/agent/images
    - /var/lib/rancher/k3s/server

- name: Download k3s binary
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}/k3s{{ "" if ansible_facts["architecture"] == "x86_64" else "-" + k3s_architecture[ansible_facts["architecture"]] }}
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}/sha256sum-{{ k3s_architecture[ansible_facts["architecture"]] }}.txt
    dest: /usr/local/bin/k3s
    mode: "0755"

- name: Create k3s symbolic links
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/{{ item }}
    mode: "0755"
    state: link
  loop:
    - crictl
    - ctr
    - kubectl

- name: Download k3s images
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}/k3s-airgap-images-{{ k3s_architecture[ansible_facts["architecture"]] }}.tar.zst
    checksum: sha256:https://github.com/k3s-io/k3s/releases/download/v{{ k3s_version }}/sha256sum-{{ k3s_architecture[ansible_facts["architecture"]] }}.txt
    dest: /var/lib/rancher/k3s/agent/images/k3s-airgap-images-{{ k3s_architecture[ansible_facts["architecture"]] }}.tar.zst
    mode: "0755"

- name: Create k3s server config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/lib/rancher/k3s/server/{{ item }}"
    mode: "0644"
  loop:
    - api-server-admission-configuration.yaml
    - audit-policy.yaml
    - event-rate-limit-configuration.yaml

- name: Create k3s config file
  ansible.builtin.copy:
    src: config.yaml
    dest: /etc/rancher/k3s/config.yaml
    mode: "0644"

- name: Configure k3s kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    state: present
    sysctl_file: /etc/sysctl.d/90-kubelet.conf
  loop:
    - name: vm.panic_on_oom
      value: 0
    - name: vm.overcommit_memory
      value: 1
    - name: kernel.panic
      value: 10
    - name: kernel.panic_on_oops
      value: 1

- name: Create k3s systemd service
  ansible.builtin.copy:
    src: k3s.service
    dest: /etc/systemd/system/k3s.service
    mode: "0644"

- name: Restart k3s systemd service
  ansible.builtin.systemd_service:
    name: k3s.service
    daemon_reload: true
    enabled: true
    state: restarted

- name: Read k3s kube config
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: k3s_config_raw

- name: Set k3s cluster facts
  ansible.builtin.set_fact:
    k3s_server: "{{ '127.0.0.1' if lookup('ansible.builtin.env', 'CI') else ansible_facts['default_ipv4']['address'] }}"
    k3s_config: "{{ k3s_config_raw['content'] | ansible.builtin.b64decode | ansible.builtin.from_yaml }}"

- name: Set k3s kube config locally
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - set
      - "{{ item.key }}"
      - "{{ item.value }}"
  loop:
    - key: "clusters.{{ k3s_server }}.server"
      value: "https://{{ k3s_server }}:6443"
    - key: "clusters.{{ k3s_server }}.certificate-authority-data"
      value: "{{ k3s_config['clusters'][0]['cluster']['certificate-authority-data'] }}"
    - key: "contexts.{{ k3s_server }}.cluster"
      value: "{{ k3s_server }}"
    - key: "contexts.{{ k3s_server }}.user"
      value: "{{ k3s_server }}"
    - key: "users.{{ k3s_server }}.client-certificate-data"
      value: "{{ k3s_config['users'][0]['user']['client-certificate-data'] }}"
    - key: "users.{{ k3s_server }}.client-key-data"
      value: "{{ k3s_config['users'][0]['user']['client-key-data'] }}"
  become: false
  delegate_to: localhost

- name: Set kubectl to k3s context
  ansible.builtin.command:
    argv:
      - kubectl
      - config
      - use-context
      - "{{ k3s_server }}"
  become: false
  delegate_to: localhost
