# renovate: datasource=git-tags depName=https://github.com/kubernetes-sigs/gateway-api extractVersion=v(?<version>.+)$
gateway_api_version: 1.5.0
gateway_api_url: "https://github.com/kubernetes-sigs/gateway-api/releases/download/v{{ gateway_api_version }}/standard-install.yaml"
